services:
  db:
    container_name: postgres-puppet-db
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: puppet_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123