services:
  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  elasticsearch:
    image: elasticsearch:${STACK_VERSION}
    container_name: elasticsearch
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
      - xpack.security.enabled=false # Disable security for local development
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk-net

  kibana:
    image: kibana:${STACK_VERSION}
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elk-net

  logstash:
    image: logstash:${STACK_VERSION}
    container_name: logstash
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch
    environment:
      - PIPELINE_WORKERS=1
      - PIPELINE_BATCH_SIZE=125
      - PIPELINE_BATCH_DELAY=50
      - LS_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ../logstash/:/logstash_dir
    command: logstash -f /logstash_dir/logstash.conf
    networks:
      - elk-net

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - elk-net

networks:
  elk-net:
volumes:
  elasticsearch_data:
  redis_data: