services:
  redis:
    image: redis:8.2.0
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - redis-network

volumes:
  redis_data:

networks:
  redis-network: